let currentUser=null,editingPartId=null;
const $=id=>document.getElementById(id);
const defaultPhoto="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100'%3E%3Crect width='100' height='100' rx='20' fill='%23d2b06f'/%3E%3Ctext x='50' y='58' font-size='38' text-anchor='middle' fill='white'%3EA%3C/text%3E%3C/svg%3E";
let users=JSON.parse(localStorage.getItem("users"))||null;
if(!users){users=[{username:"Admin",code:"ADMIN-0001",pin:"",role:"admin",active:true,lastSeen:"-",photo:defaultPhoto,device:"-",online:false,friends:[],requests:[]}];for(let i=1;i<=9999;i++)users.push({username:"",code:"ATLY-"+String(i).padStart(4,"0"),pin:"",role:"user",active:true,lastSeen:"-",photo:defaultPhoto,device:"-",online:false,friends:[],requests:[]})}
let categories=JSON.parse(localStorage.getItem("categories"))||["Elektronik","Mekanik","Kıyafet","Sensör","Motor","Kablo","Modül","Diğer"];
let parts=JSON.parse(localStorage.getItem("parts"))||[],projects=JSON.parse(localStorage.getItem("projects"))||[],orders=JSON.parse(localStorage.getItem("orders"))||[],messages=JSON.parse(localStorage.getItem("messages"))||[],exchanges=JSON.parse(localStorage.getItem("exchanges"))||[];
let updateInfo=JSON.parse(localStorage.getItem("updateInfo"))||{version:"v1.0",message:"AtölyeAI Classic Pro aktif edildi."};
function save(){localStorage.setItem("users",JSON.stringify(users));localStorage.setItem("categories",JSON.stringify(categories));localStorage.setItem("parts",JSON.stringify(parts));localStorage.setItem("projects",JSON.stringify(projects));localStorage.setItem("orders",JSON.stringify(orders));localStorage.setItem("messages",JSON.stringify(messages));localStorage.setItem("exchanges",JSON.stringify(exchanges));localStorage.setItem("updateInfo",JSON.stringify(updateInfo))}
function toast(t){$("toast").innerText=t;$("toast").classList.remove("hidden");setTimeout(()=>$("toast").classList.add("hidden"),2200)}
window.onload=()=>{save();renderCategoryOptions();let s=JSON.parse(localStorage.getItem("session")||"null");if(s){$("loginUsername").value=s.username;$("loginCode").value=s.code;$("rememberMe").checked=true;}}
function deviceInfo(){return navigator.userAgent+" | "+screen.width+"x"+screen.height+" | "+new Date().toLocaleString("tr-TR")}
function login(){let username=$("loginUsername").value.trim(),code=$("loginCode").value.trim().toUpperCase(),pin=$("loginPin").value;if(!username||!code)return alert("Kullanıcı adı ve kod yaz.");let u=users.find(x=>x.code===code);if(!u)return alert("Kod bulunamadı.");if(!u.active)return alert("Kod iptal.");if(!u.username)u.username=username;if(u.username!==username)return alert("Bu kod başka kullanıcıya ait.");if(u.pin&&u.pin!==pin)return alert("PIN yanlış.");if(!u.pin&&pin)u.pin=pin;u.lastSeen=new Date().toLocaleString("tr-TR");u.device=deviceInfo();u.online=true;currentUser=u;if($("rememberMe").checked)localStorage.setItem("session",JSON.stringify({username:u.username,code:u.code}));else localStorage.removeItem("session");save();$("loginScreen").classList.add("hidden");$("app").classList.remove("hidden");$("adminBtn").style.display=u.role==="admin"?"block":"none";renderAll();showPage("dashboard");showUpdate();toast("Giriş başarılı")}
function logout(){if(currentUser){let u=users.find(x=>x.code===currentUser.code);if(u)u.online=false;save()}localStorage.removeItem("session");location.reload()}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));$(id).classList.remove("hidden");renderAll()}
function showUpdate(){let k="seen_"+currentUser.code;if(localStorage.getItem(k)!==updateInfo.version){$("updateTitle").innerText=updateInfo.version;$("updateDesc").innerText=updateInfo.message;$("updatePopup").classList.remove("hidden")}}
function closeUpdatePopup(){localStorage.setItem("seen_"+currentUser.code,updateInfo.version);$("updatePopup").classList.add("hidden")}
function renderCategoryOptions(){$("partCategory").innerHTML=categories.map(c=>`<option>${c}</option>`).join("");$("stockSearchCategory").innerHTML=`<option value="">Tüm Kategoriler</option>`+categories.map(c=>`<option>${c}</option>`).join("")}
function addCategory(){let n=$("categoryName").value.trim();if(!n)return;if(categories.includes(n))return alert("Bu kategori var.");categories.push(n);$("categoryName").value="";save();renderAll();toast("Kategori eklendi")}
function deleteCategory(n){categories=categories.filter(c=>c!==n);parts=parts.map(p=>p.category===n?{...p,category:"Diğer"}:p);save();renderAll()}
function savePart(){let name=$("partName").value.trim();if(!name)return alert("Ürün adı boş.");let p={id:editingPartId||Date.now(),owner:currentUser.code,name,code:$("partCode").value.trim(),category:$("partCategory").value,count:+$("partCount").value||0,min:+$("partMin").value||0,box:$("partBox").value.trim(),shelf:$("partShelf").value.trim(),photo:$("partPhoto").value.trim(),note:$("partNote").value.trim()};editingPartId?parts=parts.map(x=>x.id===editingPartId?p:x):parts.push(p);editingPartId=null;clearPartForm();save();renderAll();toast("Ürün kaydedildi")}
function editPart(id){let p=parts.find(x=>x.id===id);if(!p)return;editingPartId=id;["Name","Code","Count","Min","Box","Shelf","Photo","Note"].forEach(k=>$("part"+k).value=p[k.toLowerCase()]||"");$("partCategory").value=p.category||"Diğer";showPage("stock")}
function deletePart(id){parts=parts.filter(p=>p.id!==id);save();renderAll()}
function clearPartForm(){editingPartId=null;["partName","partCode","partCount","partMin","partBox","partShelf","partPhoto","partNote"].forEach(id=>$(id).value="")}
function myParts(){return parts.filter(p=>p.owner===currentUser.code)}
function checkStock(){let t=$("stockSearchInput").value.trim().toLowerCase(),c=$("stockSearchCategory").value;let f=myParts().filter(p=>(!t||p.name.toLowerCase().includes(t)||(p.code||"").toLowerCase().includes(t)||(p.category||"").toLowerCase().includes(t))&&(!c||p.category===c));$("stockCheckResult").innerHTML=f.length?f.map(stockCard).join(""):"<div class='item'>Sonuç bulunamadı.</div>"}
function clearStockCheck(){$("stockSearchInput").value="";$("stockSearchCategory").value="";$("stockCheckResult").innerHTML=""}
function stockCard(p){let cls=p.count<=0?"bad":p.count<p.min?"warn":"ok",st=p.count<=0?"Bitti":p.count<p.min?"Az stok":"Yeterli";return `<div class="item">${p.photo?`<img class="product-img" src="${p.photo}">`:""}<div class="item-text"><b>${p.name}</b><br>Kod: ${p.code||"-"}<br>Kategori: ${p.category}<br>Adet: ${p.count} / Min: ${p.min}<br>Konum: ${p.box||"-"} / ${p.shelf||"-"}<br><span class="badge ${cls}">${st}</span></div></div>`}
function addProject(){if(!$("projectName").value.trim())return;projects.push({id:Date.now(),owner:currentUser.code,name:$("projectName").value.trim(),status:$("projectStatus").value,parts:$("projectParts").value.trim(),note:$("projectNote").value.trim()});$("projectName").value=$("projectParts").value=$("projectNote").value="";save();renderAll()}
function changeProjectStatus(id,s){let p=projects.find(x=>x.id===id);if(p){p.status=s;save();renderAll()}}
function deleteProject(id){projects=projects.filter(p=>p.id!==id);save();renderAll()}
function addOrder(){if(!$("orderName").value.trim())return;orders.push({id:Date.now(),owner:currentUser.code,name:$("orderName").value.trim(),count:+$("orderCount").value||0,price:+$("orderPrice").value||0,link:$("orderLink").value.trim(),status:$("orderStatus").value});["orderName","orderCount","orderPrice","orderLink"].forEach(id=>$(id).value="");save();renderAll()}
function changeOrderStatus(id,s){let o=orders.find(x=>x.id===id);if(o){o.status=s;save();renderAll()}}
function deleteOrder(id){orders=orders.filter(o=>o.id!==id);save();renderAll()}
function sendMessage(){let text=$("messageText").value.trim(),type=$("messageType").value,to=$("messageTo").value.trim();if(!text)return;if(type==="private"&&!to)return alert("Kullanıcı adı yaz.");messages.push({id:Date.now(),user:currentUser.username,to,type,text,date:new Date().toLocaleString("tr-TR")});$("messageText").value="";save();renderAll()}
function deleteMessage(id){messages=messages.filter(m=>m.id!==id);save();renderAll()}
function saveProfile(){let n=$("profileName").value.trim(),pin=$("profilePin").value,photo=$("profilePhoto").value.trim();if(n)currentUser.username=n;if(pin)currentUser.pin=pin;if(photo)currentUser.photo=photo;let u=users.find(x=>x.code===currentUser.code);Object.assign(u,currentUser);save();renderAll();toast("Profil kaydedildi")}
function sendFriendRequest(){let name=$("friendName").value.trim();let target=users.find(u=>u.username===name);if(!target||target.code===currentUser.code)return alert("Kullanıcı bulunamadı.");if(!target.requests)target.requests=[];if(!target.requests.includes(currentUser.code))target.requests.push(currentUser.code);save();renderAll();toast("İstek gönderildi")}
function acceptFriend(code){let me=users.find(u=>u.code===currentUser.code),other=users.find(u=>u.code===code);me.requests=(me.requests||[]).filter(x=>x!==code);me.friends=[...(me.friends||[]),code];other.friends=[...(other.friends||[]),me.code];save();renderAll()}
function sendExchangeRequest(){let toUser=users.find(u=>u.username===$("exchangeTo").value.trim());if(!toUser)return alert("Kullanıcı yok.");exchanges.push({id:Date.now(),from:currentUser.code,to:toUser.code,type:$("exchangeType").value,want:$("exchangeWant").value,offer:$("exchangeOffer").value,status:"Bekliyor"});save();renderAll()}
function setExchange(id,status){let e=exchanges.find(x=>x.id===id);if(e){e.status=status;save();renderAll()}}
function publishUpdate(){if(currentUser.role!=="admin")return;updateInfo={version:$("updateVersionInput").value||("v"+Date.now()),message:$("updateMessageInput").value||"Sistem güncellendi."};save();toast("Duyuru yayınlandı")}
function askAI(){let q=$("aiInput").value.toLowerCase();$("aiChat").innerHTML+=`<div class="ai-msg"><b>Sen:</b> ${$("aiInput").value}</div>`;let low=myParts().filter(p=>p.count<p.min),ans="Stok, proje, sipariş, arkadaş ve takas analizi yapabilirim.";if(q.includes("az")||q.includes("eksik"))ans=low.length?low.map(p=>`${p.name}: ${p.count}/${p.min}`).join("<br>"):"Az stok yok.";else if(q.includes("kategori"))ans=categories.map(c=>`${c}: ${myParts().filter(p=>p.category===c).length}`).join("<br>");else if(q.includes("harcama"))ans="Toplam: "+orders.filter(o=>o.owner===currentUser.code).reduce((s,o)=>s+o.price*o.count,0)+" TL";$("aiChat").innerHTML+=`<div class="ai-msg"><b>AI:</b><br>${ans}</div>`;$("aiInput").value=""}
function getMaterialStatus(n){let f=myParts().find(p=>p.name.toLowerCase().includes(n.trim().toLowerCase()));if(!f)return `<span class="badge bad">${n} yok</span>`;if(f.count<f.min)return `<span class="badge warn">${n} az</span>`;return `<span class="badge ok">${n} var</span>`}
function renderProjectMaterials(p){return p.parts?p.parts.split(",").map(x=>x.trim()).filter(Boolean).map(getMaterialStatus).join(" "):"-"}
function renderAll(){renderCategoryOptions();renderDashboard();renderStock();renderCategories();renderProjects();renderOrders();renderMessages();renderFriends();renderExchange();renderReports();if(currentUser?.role==="admin")renderAdmin()}
function renderDashboard(){let mp=myParts(),low=mp.filter(p=>p.count<p.min),ao=orders.filter(o=>o.owner===currentUser.code),cart=ao.filter(o=>o.status==="Alınacak").reduce((s,o)=>s+o.price*o.count,0),del=ao.filter(o=>o.status==="Teslim edildi").reduce((s,o)=>s+o.price*o.count,0),wait=ao.filter(o=>o.status!=="Teslim edildi"&&o.status!=="İptal edildi").reduce((s,o)=>s+o.price*o.count,0);$("totalProducts").innerText=mp.length;$("lowStockCount").innerText=low.length;$("categoryCount").innerText=categories.length;$("activeProjectCount").innerText=projects.filter(p=>p.owner===currentUser.code&&p.status!=="Bitti").length;$("totalSpend").innerText=cart+del+wait+" TL";$("cartTotal").innerText=cart+" TL";$("deliveredTotal").innerText=del+" TL";$("waitingTotal").innerText=wait+" TL";drawChart(cart,del,wait);$("notifications").innerHTML=low.map(p=>`<p>${p.name} az stokta.</p>`).join("")||"<p>Bildirim yok.</p>";$("buyList").innerHTML=ao.filter(o=>o.status==="Alınacak").map(o=>`<p>${o.name} - ${o.count}</p>`).join("")||"<p>Yok.</p>";$("stockMini").innerHTML=mp.slice(-4).map(p=>`<p>${p.name} — ${p.count}</p>`).join("")||"<p>Ürün yok.</p>";$("projectMini").innerHTML=projects.filter(p=>p.owner===currentUser.code).slice(0,3).map(p=>`<p>${p.name} — ${p.status}</p>`).join("")||"<p>Proje yok.</p>";$("activeUsers").innerHTML=users.filter(u=>u.username&&u.online).map(u=>`<p>🟢 ${u.username}<br><small>${u.lastSeen}</small></p>`).join("")||"<p>Aktif yok.</p>";$("lastMessages").innerHTML=messages.slice(-5).map(m=>`<p><b>${m.user}</b>: ${m.text}</p>`).join("")||"<p>Mesaj yok.</p>";$("welcomeTitle").innerText="Hoş geldin, "+currentUser.username;$("userInfo").innerText=currentUser.username+" | "+currentUser.role;$("userCodeInfo").innerText=currentUser.code;$("miniPhoto").src=currentUser.photo||defaultPhoto;$("accountPhoto").src=currentUser.photo||defaultPhoto;$("accountName").innerText=currentUser.username;$("accountRole").innerText=currentUser.role;$("accountLastSeen").innerText=currentUser.lastSeen}
function renderStock(){let mp=myParts();$("stockList").innerHTML=mp.length?mp.map(p=>`<div class="item">${p.photo?`<img class="product-img" src="${p.photo}">`:""}<div class="item-text"><b>${p.name}</b><br>${p.category} | ${p.count}/${p.min}<br>${p.box||"-"} / ${p.shelf||"-"}<br>${p.note||""}</div><div><button class="small-btn success" onclick="editPart(${p.id})">Düzenle</button><button class="small-btn danger" onclick="deletePart(${p.id})">Sil</button></div></div>`).join(""):"<p>Ürün yok.</p>"}
function renderCategories(){$("categoryList").innerHTML=categories.map(c=>`<div class="item"><div><b>${c}</b><br>${myParts().filter(p=>p.category===c).length} ürün</div><button class="small-btn danger" onclick="deleteCategory('${c}')">Sil</button></div>`).join("")}
function renderProjects(){$("projectList").innerHTML=projects.filter(p=>p.owner===currentUser.code).map(p=>`<div class="item"><div class="item-text"><b>${p.name}</b><br>${p.status}<div class="project-materials">${renderProjectMaterials(p)}</div></div><div><select onchange="changeProjectStatus(${p.id},this.value)"><option ${p.status==="Planlandı"?"selected":""}>Planlandı</option><option ${p.status==="Devam ediyor"?"selected":""}>Devam ediyor</option><option ${p.status==="Bitti"?"selected":""}>Bitti</option></select><button class="small-btn danger" onclick="deleteProject(${p.id})">Sil</button></div></div>`).join("")||"<p>Proje yok.</p>"}
function renderOrders(){$("orderList").innerHTML=orders.filter(o=>o.owner===currentUser.code).map(o=>`<div class="item"><div><b>${o.name}</b><br>${o.count} adet x ${o.price} TL = ${o.count*o.price} TL<br>${o.status}</div><div><select onchange="changeOrderStatus(${o.id},this.value)"><option ${o.status==="Alınacak"?"selected":""}>Alınacak</option><option ${o.status==="Sipariş verildi"?"selected":""}>Sipariş verildi</option><option ${o.status==="Kargoda"?"selected":""}>Kargoda</option><option ${o.status==="Teslim edildi"?"selected":""}>Teslim edildi</option><option ${o.status==="İptal edildi"?"selected":""}>İptal edildi</option></select><button class="small-btn danger" onclick="deleteOrder(${o.id})">Sil</button></div></div>`).join("")||"<p>Sipariş yok.</p>"}
function renderMessages(){let v=messages.filter(m=>m.type==="general"||m.user===currentUser.username||m.to===currentUser.username||currentUser.role==="admin");$("messageList").innerHTML=v.map(m=>`<div class="item ${m.type==="private"?"private-bubble":"message-bubble"}"><div><b>${m.user}</b> ${m.type==="private"?"→ "+m.to:""}<br>${m.text}</div>${currentUser.role==="admin"?`<button class="small-btn danger" onclick="deleteMessage(${m.id})">Sil</button>`:""}</div>`).join("")||"<p>Mesaj yok.</p>"}
function renderFriends(){let me=users.find(u=>u.code===currentUser.code);$("friendList").innerHTML=(me.friends||[]).map(c=>users.find(u=>u.code===c)).filter(Boolean).map(u=>`<p><b>${u.username}</b> (${u.code})</p>`).join("")||"<p>Arkadaş yok.</p>";$("friendRequests").innerHTML=(me.requests||[]).map(c=>{let u=users.find(x=>x.code===c);return `<div class="item"><span>${u?.username||c}</span><button class="small-btn success" onclick="acceptFriend('${c}')">Kabul Et</button></div>`}).join("")||"<p>İstek yok.</p>";$("friendInventories").innerHTML=(me.friends||[]).map(c=>{let u=users.find(x=>x.code===c),inv=parts.filter(p=>p.owner===c);return `<div class="item"><div><b>${u?.username}</b><br>${inv.map(p=>p.name+" ("+p.count+")").join(", ")||"Envanter boş"}</div></div>`}).join("")}
function renderExchange(){$("exchangeList").innerHTML=exchanges.filter(e=>e.from===currentUser.code||e.to===currentUser.code||currentUser.role==="admin").map(e=>{let f=users.find(u=>u.code===e.from),t=users.find(u=>u.code===e.to);return `<div class="item"><div><b>${e.type}</b><br>${f?.username} → ${t?.username}<br>İstenen: ${e.want}<br>Teklif: ${e.offer}<br>Durum: ${e.status}</div>${e.to===currentUser.code?`<div><button class="small-btn success" onclick="setExchange(${e.id},'Kabul')">Kabul</button><button class="small-btn danger" onclick="setExchange(${e.id},'Red')">Red</button></div>`:""}</div>`}).join("")||"<p>İstek yok.</p>"}
function renderReports(){$("categoryReport").innerHTML=categories.map(c=>`<p>${c}: ${myParts().filter(p=>p.category===c).length}</p>`).join("");$("orderReport").innerHTML=`<p>Toplam sipariş: ${orders.filter(o=>o.owner===currentUser.code).length}</p>`}
function renderAdmin(){let s=$("searchCode").value.trim().toUpperCase(),list=s?users.filter(u=>u.code.includes(s)||u.username.toUpperCase().includes(s)):users.slice(0,100);$("codeList").innerHTML=list.map(u=>`<div class="item"><div><b>${u.code}</b><br>${u.username||"Boşta"} | ${u.role}<br>Aktif: ${u.online?"Evet":"Hayır"}<br>Cihaz: ${u.device||"-"}</div><div><button class="small-btn danger" onclick="cancelCode('${u.code}')">İptal</button><button class="small-btn success" onclick="resetCode('${u.code}')">Sıfırla</button></div></div>`).join("");$("adminInventories").innerHTML=users.filter(u=>u.username).map(u=>`<div class="item"><div><b>${u.username}</b><br>${parts.filter(p=>p.owner===u.code).map(p=>p.name+" ("+p.count+")").join(", ")||"Envanter boş"}</div></div>`).join("")}
function cancelCode(c){let u=users.find(x=>x.code===c);if(u){u.active=false;save();renderAdmin()}}function resetCode(c){let u=users.find(x=>x.code===c);if(u){u.username="";u.pin="";u.active=true;u.friends=[];u.requests=[];save();renderAdmin()}}
function drawChart(cart,del,wait){let c=$("spendChart");if(!c)return;let ctx=c.getContext("2d"),w=c.width=c.offsetWidth,h=c.height=170;ctx.clearRect(0,0,w,h);let arr=[["Sepet",cart,"#b08d57"],["Teslim",del,"#15803d"],["Bekleyen",wait,"#b45309"]],max=Math.max(cart,del,wait,1),bw=w/3-35;arr.forEach((a,i)=>{let x=i*(bw+35)+20,bh=a[1]/max*95,y=h-bh-30;ctx.fillStyle=a[2];ctx.roundRect(x,y,bw,bh,10);ctx.fill();ctx.fillStyle="#1f2933";ctx.font="bold 12px Arial";ctx.fillText(a[0],x,h-8);ctx.fillText(a[1]+" TL",x,y-8)})}
