let currentUser=null,editingPartId=null;
let users=JSON.parse(localStorage.getItem("users"));
if(!users){users=[{username:"Admin",code:"ADMIN-0001",role:"admin",active:true,lastSeen:"-"}];for(let i=1;i<=9999;i++)users.push({username:"",code:"ATLY-"+String(i).padStart(4,"0"),role:"user",active:true,lastSeen:"-"});localStorage.setItem("users",JSON.stringify(users))}
let categories=JSON.parse(localStorage.getItem("categories"))||["Elektronik","Mekanik","Sensör","Kablo","Güç","Vida-Somun","Diğer"];
let parts=JSON.parse(localStorage.getItem("parts"))||[],projects=JSON.parse(localStorage.getItem("projects"))||[],orders=JSON.parse(localStorage.getItem("orders"))||[],messages=JSON.parse(localStorage.getItem("messages"))||[];
let updateInfo=JSON.parse(localStorage.getItem("updateInfo"))||{version:1,title:"Hoş geldin",desc:"AtölyeAI Nexus aktif."};
if(localStorage.getItem("theme")==="dark")document.body.classList.add("dark");
function saveData(){localStorage.setItem("users",JSON.stringify(users));localStorage.setItem("categories",JSON.stringify(categories));localStorage.setItem("parts",JSON.stringify(parts));localStorage.setItem("projects",JSON.stringify(projects));localStorage.setItem("orders",JSON.stringify(orders));localStorage.setItem("messages",JSON.stringify(messages));localStorage.setItem("updateInfo",JSON.stringify(updateInfo))}
function toast(t){toastEl=document.getElementById("toast");toastEl.innerText=t;toastEl.classList.remove("hidden");setTimeout(()=>toastEl.classList.add("hidden"),2200)}
function login(){let username=loginUsername.value.trim(),code=loginCode.value.trim().toUpperCase();if(!username||!code)return alert("Kullanıcı adı ve kod yaz.");let user=users.find(u=>u.code===code);if(!user)return alert("Kod yok.");if(!user.active)return alert("Kod iptal edilmiş.");if(!user.username)user.username=username;if(user.username!==username)return alert("Bu kod başka kullanıcıya ait.");user.lastSeen=new Date().toLocaleString("tr-TR");currentUser=user;saveData();loginScreen.classList.add("hidden");app.classList.remove("hidden");welcomeTitle.innerText="Hoş geldin, "+user.username+" 👋";userInfo.innerText=user.username+" | "+user.role;userCodeInfo.innerText=user.code;adminBtn.style.display=user.role==="admin"?"block":"none";renderCategorySelect();showPage("dashboard");checkUpdatePopup()}
function checkUpdatePopup(){let seen=localStorage.getItem("seenUpdate_"+currentUser.code);if(seen!=updateInfo.version){updateTitleText.innerText=updateInfo.title;updateDescText.innerText=updateInfo.desc;updateModal.classList.remove("hidden")}}
function closeUpdateModal(){localStorage.setItem("seenUpdate_"+currentUser.code,updateInfo.version);updateModal.classList.add("hidden")}
function publishUpdate(){if(currentUser.role!=="admin")return;updateInfo={version:Date.now(),title:updateTitle.value||"Yeni güncelleme",desc:updateDesc.value||"Sistemde yeni değişiklikler yapıldı."};saveData();toast("Güncelleme yayınlandı")}
function logout(){location.reload()}function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");renderAll()}function toggleTheme(){document.body.classList.toggle("dark");localStorage.setItem("theme",document.body.classList.contains("dark")?"dark":"light");renderAll()}
function renderCategorySelect(){partCategory.innerHTML=categories.map(c=>`<option>${c}</option>`).join("")}
function addCategory(){let n=categoryName.value.trim();if(!n)return;if(categories.includes(n))return alert("Bu kategori var.");categories.push(n);categoryName.value="";saveData();renderCategorySelect();renderAll();toast("Kategori eklendi")}
function deleteCategory(n){if(parts.some(p=>p.category===n))return alert("Bu kategoride ürün var, önce ürünleri değiştir.");categories=categories.filter(c=>c!==n);saveData();renderCategorySelect();renderAll()}
function savePart(){let name=partName.value.trim();if(!name)return alert("Ürün adı boş.");let part={id:editingPartId||Date.now(),name,code:partCode.value.trim(),category:partCategory.value,count:+partCount.value||0,min:+partMin.value||0,box:partBox.value.trim(),shelf:partShelf.value.trim(),photo:partPhoto.value.trim(),note:partNote.value.trim()};editingPartId?parts=parts.map(p=>p.id===editingPartId?part:p):parts.push(part);editingPartId=null;clearPartForm();saveData();renderAll()}
function editPart(id){let p=parts.find(x=>x.id===id);if(!p)return;editingPartId=id;partName.value=p.name;partCode.value=p.code||"";partCategory.value=p.category||"Diğer";partCount.value=p.count;partMin.value=p.min;partBox.value=p.box||"";partShelf.value=p.shelf||"";partPhoto.value=p.photo||"";partNote.value=p.note||"";showPage("stock")}
function deletePart(id){if(confirm("Silinsin mi?")){parts=parts.filter(p=>p.id!==id);saveData();renderAll()}}function clearPartForm(){editingPartId=null;["partName","partCode","partCount","partMin","partBox","partShelf","partPhoto","partNote"].forEach(id=>document.getElementById(id).value="")}
function checkStock(){let q=stockSearchInput.value.trim().toLowerCase();if(!q){stockCheckResult.innerHTML="<p>Arama yaz.</p>";return}let f=parts.filter(p=>p.name.toLowerCase().includes(q)||(p.code||"").toLowerCase().includes(q)||(p.category||"").toLowerCase().includes(q));stockCheckResult.innerHTML=f.length?f.map(stockCard).join(""):"<div class='item'><div class='item-text'>❌ Ürün bulunamadı.</div></div>"}
function addProject(){if(!projectName.value.trim())return;projects.push({id:Date.now(),name:projectName.value.trim(),status:projectStatus.value,parts:projectParts.value.trim(),note:projectNote.value.trim()});projectName.value=projectParts.value=projectNote.value="";saveData();renderAll()}
function changeProjectStatus(id,s){let p=projects.find(x=>x.id===id);if(p){p.status=s;saveData();renderAll()}}function deleteProject(id){projects=projects.filter(p=>p.id!==id);saveData();renderAll()}
function addOrder(){if(!orderName.value.trim())return;orders.push({id:Date.now(),name:orderName.value.trim(),count:+orderCount.value||0,price:+orderPrice.value||0,link:orderLink.value.trim(),status:orderStatus.value});["orderName","orderCount","orderPrice","orderLink"].forEach(id=>document.getElementById(id).value="");saveData();renderAll()}
function changeOrderStatus(id,s){let o=orders.find(x=>x.id===id);if(o){o.status=s;saveData();renderAll()}}function deleteOrder(id){orders=orders.filter(o=>o.id!==id);saveData();renderAll()}
function sendMessage(){let text=messageText.value.trim(),type=messageType.value,to=messageTo.value.trim();if(!text)return;if(type==="private"&&!to)return alert("Kullanıcı adı yaz.");messages.push({id:Date.now(),user:currentUser.username,to,type,text,date:new Date().toLocaleString("tr-TR")});messageText.value="";saveData();renderAll()}
function deleteMessage(id){messages=messages.filter(m=>m.id!==id);saveData();renderAll()}function cancelCode(c){let u=users.find(x=>x.code===c);if(u){u.active=false;saveData();renderAdmin()}}function resetCode(c){let u=users.find(x=>x.code===c);if(u){u.username="";u.active=true;saveData();renderAdmin()}}
function getMaterialStatus(n){let c=n.trim().toLowerCase(),f=parts.find(p=>p.name.toLowerCase().includes(c)||(p.code||"").toLowerCase().includes(c));if(!f)return `<span class="badge bad">❌ ${n} yok</span>`;if(f.count<=0)return `<span class="badge bad">❌ ${n} bitti</span>`;if(f.count<f.min)return `<span class="badge warn">⚠️ ${n} az (${f.count})</span>`;return `<span class="badge ok">✅ ${n} var (${f.count})</span>`}
function renderProjectMaterials(p){return p.parts?p.parts.split(",").map(x=>x.trim()).filter(Boolean).map(getMaterialStatus).join(" "):"Malzeme yok."}
function askAI(){let q=aiInput.value.trim().toLowerCase();if(!q)return;aiChat.innerHTML+=`<div class="ai-msg ai-user"><b>Sen:</b> ${aiInput.value}</div>`;let low=parts.filter(p=>p.count<p.min),ans="Ben stok, kategori, sipariş, proje ve harcama analizi yapabilirim.";if(q.includes("eksik")||q.includes("az"))ans=low.length?low.map(p=>`⚠️ ${p.name}: ${p.count}/${p.min}`).join("<br>"):"✅ Az stok yok.";else if(q.includes("kategori"))ans=categories.map(c=>`🏷️ ${c}: ${parts.filter(p=>p.category===c).length} ürün`).join("<br>");else if(q.includes("harcama"))ans=`💸 Toplam: ${orders.reduce((s,o)=>s+o.price*o.count,0)} TL`;else if(q.includes("proje"))ans=projects.map(p=>`🛠️ ${p.name}<br>${renderProjectMaterials(p)}`).join("<hr>")||"Proje yok.";aiChat.innerHTML+=`<div class="ai-msg"><b>AtölyeAI:</b><br>${ans}</div>`;aiInput.value=""}
function renderAll(){renderCategorySelect();renderDashboard();renderStock();renderCategories();renderProjects();renderOrders();renderMessages();renderReports();if(currentUser&&currentUser.role==="admin")renderAdmin()}
function renderDashboard(){let low=parts.filter(p=>p.count<p.min),active=projects.filter(p=>p.status!=="Bitti"),pending=orders.filter(o=>o.status!=="Teslim edildi"&&o.status!=="İptal edildi"),cart=orders.filter(o=>o.status==="Alınacak").reduce((s,o)=>s+o.price*o.count,0),del=orders.filter(o=>o.status==="Teslim edildi").reduce((s,o)=>s+o.price*o.count,0),wait=pending.reduce((s,o)=>s+o.price*o.count,0);totalProducts.innerText=parts.length;lowStockCount.innerText=low.length;activeProjectCount.innerText=active.length;pendingOrderCount.innerText=pending.length;totalSpend.innerText=(cart+del+wait)+" TL";cartTotal.innerText=cart+" TL";deliveredTotal.innerText=del+" TL";waitingTotal.innerText=wait+" TL";drawChart(cart,del,wait);notifications.innerHTML=low.length?low.slice(0,5).map(p=>`<p>⚠️ ${p.name} az.</p>`).join(""):"<p>✅ Bildirim yok.</p>";buyList.innerHTML=orders.filter(o=>o.status==="Alınacak").slice(0,5).map(o=>`<p>🛒 ${o.name} - ${o.count}</p>`).join("")||"<p>Yok.</p>";stockMini.innerHTML=parts.slice(-4).reverse().map(p=>`<p>🔧 ${p.name} — ${p.count}</p>`).join("")||"<p>Ürün yok.</p>";categoryMini.innerHTML=categories.slice(0,6).map(c=>`<p>🏷️ ${c}: ${parts.filter(p=>p.category===c).length}</p>`).join("");activeUsers.innerHTML=users.filter(u=>u.username&&u.active).slice(0,8).map(u=>`<p>🟢 ${u.username}<br><small>${u.lastSeen}</small></p>`).join("");lastMessages.innerHTML=messages.slice(-5).reverse().map(m=>`<p>💬 <b>${m.user}</b>: ${m.text}</p>`).join("")||"<p>Mesaj yok.</p>";if(currentUser){accountName.innerText=currentUser.username;accountRole.innerText=currentUser.role==="admin"?"👑 Admin":"👤 Üye";accountLastSeen.innerText="Son giriş: "+currentUser.lastSeen}}
function stockCard(p){let cls=p.count<=0?"bad":p.count<p.min?"warn":"ok",st=p.count<=0?"❌ Bitti":p.count<p.min?"⚠️ Az stok":"✅ Yeterli";return `<div class="item">${p.photo?`<img class="product-img" src="${p.photo}">`:""}<div class="item-text"><b>🔧 ${p.name}</b><br>🏷️ ${p.code||"-"}<br>📁 ${p.category||"-"}<br>📦 ${p.count} | ⚠️ ${p.min}<br>🗃️ ${p.box||"-"} / ${p.shelf||"-"}<br><span class="badge ${cls}">${st}</span></div></div>`}
function renderStock(){stockList.innerHTML=parts.length?parts.map(p=>`<div class="item">${p.photo?`<img class="product-img" src="${p.photo}">`:""}<div class="item-text"><b>🔧 ${p.name}</b><br>🏷️ ${p.code||"-"}<br>📁 ${p.category||"-"}<br>📦 ${p.count} | ⚠️ ${p.min}<br>🗃️ ${p.box||"-"} / ${p.shelf||"-"}<br>📝 ${p.note||"-"}</div><div><button class="small-btn success" onclick="editPart(${p.id})">✏️ Düzenle</button><button class="small-btn danger" onclick="deletePart(${p.id})">🗑️ Sil</button></div></div>`).join(""):"<p>Ürün yok.</p>"}
function renderCategories(){categoryList.innerHTML=categories.map(c=>`<div class="item"><div class="item-text"><b>🏷️ ${c}</b><br>${parts.filter(p=>p.category===c).length} ürün</div><button class="small-btn danger" onclick="deleteCategory('${c}')">Sil</button></div>`).join("")}
function renderProjects(){projectList.innerHTML=projects.length?projects.map(p=>`<div class="item"><div class="item-text"><b>🛠️ ${p.name}</b><br>Durum: ${p.status}<br>${p.note||"-"}<div class="project-materials">${renderProjectMaterials(p)}</div></div><div><select onchange="changeProjectStatus(${p.id},this.value)"><option ${p.status==="Planlandı"?"selected":""}>Planlandı</option><option ${p.status==="Devam ediyor"?"selected":""}>Devam ediyor</option><option ${p.status==="Bitti"?"selected":""}>Bitti</option></select><button class="small-btn danger" onclick="deleteProject(${p.id})">Sil</button></div></div>`).join(""):"<p>Proje yok.</p>"}
function renderOrders(){orderList.innerHTML=orders.length?orders.map(o=>`<div class="item"><div class="item-text"><b>🛒 ${o.name}</b><br>🔢 ${o.count}<br>💸 Birim: ${o.price} TL<br>🧾 Toplam: ${o.price*o.count} TL<br>🚚 ${o.status}<br>${o.link?`<a href="${o.link}" target="_blank">Aç</a>`:"-"}</div><div><select onchange="changeOrderStatus(${o.id},this.value)"><option ${o.status==="Alınacak"?"selected":""}>Alınacak</option><option ${o.status==="Sipariş verildi"?"selected":""}>Sipariş verildi</option><option ${o.status==="Kargoda"?"selected":""}>Kargoda</option><option ${o.status==="Teslim edildi"?"selected":""}>Teslim edildi</option><option ${o.status==="İptal edildi"?"selected":""}>İptal edildi</option></select><button class="small-btn danger" onclick="deleteOrder(${o.id})">Sil</button></div></div>`).join(""):"<p>Sipariş yok.</p>"}
function renderMessages(){let v=messages.filter(m=>m.type==="general"||m.user===currentUser?.username||m.to===currentUser?.username||currentUser?.role==="admin");messageList.innerHTML=v.length?v.map(m=>`<div class="item ${m.type==="private"?"private-bubble":"message-bubble"}"><div class="item-text"><b>${m.user}</b> ${m.type==="private"?`➡️ ${m.to}`:"🌍 Genel"}<br>${m.text}</div>${currentUser?.role==="admin"?`<button class="small-btn danger" onclick="deleteMessage(${m.id})">Sil</button>`:""}</div>`).join(""):"<p>Mesaj yok.</p>"}
function renderReports(){categoryReport.innerHTML=categories.map(c=>`<p>🏷️ ${c}: <b>${parts.filter(p=>p.category===c).length}</b></p>`).join("");orderReport.innerHTML=`<p>🧾 Sipariş: <b>${orders.length}</b></p><p>💸 Toplam: <b>${orders.reduce((s,o)=>s+o.price*o.count,0)} TL</b></p>`}
function renderAdmin(){let s=searchCode.value.trim().toUpperCase(),list=s?users.filter(u=>u.code.includes(s)||u.username.toUpperCase().includes(s)):users.slice(0,50);codeList.innerHTML=list.map(u=>`<div class="item"><div class="item-text"><b>${u.code}</b><br>Kullanıcı: ${u.username||"Boşta"}<br>Rol: ${u.role}<br>Son giriş: ${u.lastSeen}<br>Durum: ${u.active?"Aktif":"İptal"}</div>${u.role!=="admin"?`<div><button class="small-btn danger" onclick="cancelCode('${u.code}')">İptal</button><button class="small-btn success" onclick="resetCode('${u.code}')">Sıfırla</button></div>`:""}</div>`).join("")}
function drawChart(cart,del,wait){let c=spendChart,ctx=c.getContext("2d"),w=c.width=c.offsetWidth,h=c.height=180;ctx.clearRect(0,0,w,h);let a=[["Sepet",cart,"#0284c7"],["Teslim",del,"#22c55e"],["Bekleyen",wait,"#f97316"]],max=Math.max(cart,del,wait,1),bw=w/3-35;a.forEach((x,i)=>{let bx=i*(bw+35)+20,bh=x[1]/max*105,y=h-bh-35;ctx.fillStyle=x[2];ctx.roundRect(bx,y,bw,bh,12);ctx.fill();ctx.fillStyle=document.body.classList.contains("dark")?"#fff":"#0f172a";ctx.font="bold 13px Arial";ctx.fillText(x[0],bx,h-12);ctx.fillText(x[1]+" TL",bx,y-8)})}
